version: '3'

services:
  app:
    build:
      context: '.'
    environment:
      WEBROOT: '/var/www/html/public'
      PAGER: 'more'
    env_file:
      - '.env'
    volumes:
      - './:/var/www/html'
